language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
# before_install:
# - openssl aes-256-cbc -K $encrypted_71c4271895df_key -iv $encrypted_71c4271895df_iv
#   -in id_rsa.enc -out ~/.ssh/id_rsa -d
# - chmod 600 ~/.ssh/id_rsa
# - echo -e "Host 39.106.201.195\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- npm install
before_script: 
script:
- npm run build
after_script:
- rsync -avz -e --delete ./dist/* root@39.106.201.195:/data/www
branches:
  only:
  - master

