language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
install:
- npm install
before_script: 
script:
- npm run build
after_script:
- rsync -avz -e ./dist/* root@39.106.201.195:/data/www
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_71c4271895df_key -iv $encrypted_71c4271895df_iv
  -in travis_rsa.enc -out ~/.ssh/travis_rsa -d
